-- MySQL Script generated by MySQL Workbench
-- Tue Jun  5 20:03:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blog_cice
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog_cice
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog_cice` DEFAULT CHARACTER SET utf8 ;
USE `blog_cice` ;

-- -----------------------------------------------------
-- Table `blog_cice`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_cice`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `createDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastLogin` DATETIME NULL,
  PRIMARY KEY (`idusuarios`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog_cice`.`entradas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_cice`.`entradas` (
  `identradas` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(120) NOT NULL,
  `subtitulo` VARCHAR(120) NOT NULL,
  `createDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `cuerpo` LONGTEXT NOT NULL,
  `imagenDestacada` VARCHAR(255) NOT NULL,
  `usuarios_idusuarios` INT NOT NULL,
  PRIMARY KEY (`identradas`),
  INDEX `fk_entradas_usuarios_idx` (`usuarios_idusuarios` ASC),
  CONSTRAINT `fk_entradas_usuarios`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `blog_cice`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog_cice`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_cice`.`comentarios` (
  `idcomentarios` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `mensaje` VARCHAR(144) NOT NULL,
  `createDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarios_idusuarios` INT NOT NULL,
  `entradas_identradas` INT NOT NULL,
  PRIMARY KEY (`idcomentarios`),
  INDEX `fk_comentarios_usuarios1_idx` (`usuarios_idusuarios` ASC),
  INDEX `fk_comentarios_entradas1_idx` (`entradas_identradas` ASC),
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `blog_cice`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_entradas1`
    FOREIGN KEY (`entradas_identradas`)
    REFERENCES `blog_cice`.`entradas` (`identradas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
